# Generated by Django 3.0.3 on 2020-02-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200215_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products_name',
            new_name='product_name',
        ),
    ]
